name: Main branch build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-branch-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: [ "3.10" ]

    steps:
      - name: Checkout sources  # Clones your repository into the machine running the action
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          python -m pip install -e .

      - name: Run tests
        run: poetry run python -m unittest discover tests

      - name: Coverage run
        run: |
          poetry run coverage run -m unittest discover tests
          poetry run coverage report -m --fail-under 80
          poetry run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true