name: Push

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          python -m pip install -e .
          pip install pandas

      - name: Run tests
        run: python -m unittest discover tests